project:
  type: book
  output-dir: docs

book:
  title: "Network Science"
  subtitle: "Concepts, Examples, and Exercises"
  author: "Zahra Rezaei"
  date: today
  chapters:
    - index.qmd
    - chapters/03-random-graphs.qmd
    - chapters/04-random-graph-evolution.qmd
    - chapters/05-small-world-graphs.qmd
    - chapters/06-scale-free-graphs.qmd
  page-navigation: true
  search: true

execute:
  echo: true
  warning: false
  message: false
  freeze: auto

format:
  html:
    theme:
      - cosmo
      - styles.scss
    page-layout: full           
    toc-depth: 3
    toc-location: right
    number-sections: true
    number-depth: 2
    code-copy: true
    code-fold: true
    code-summary: "Show code"
    code-overflow: wrap
    smooth-scroll: true
    anchor-sections: true
    html-math-method: katex
    df-print: paged
    fig-align: center
    fig-width: 7
    fig-height: 4.6
    fig-cap-location: bottom
    format-links:
      - pdf

  pdf:
    documentclass: report
    pdf-engine: xelatex
    latex-auto-install: true
    toc: true
    toc-depth: 3
    number-sections: true
    colorlinks: true
    geometry:
      - margin=1in
    fig-align: center
    fig-width: 6.5
    fig-height: 4.2
    fig-cap-location: bottom


editor: visual
knitr: 
  opts_chunk: 
    dev: "ragg_png"
